### ISSUE TITLE
2 issues. #1 claim should be priotized before clicking play,  #2 instant click, is unatural.

### ISSUE THREAD

**Issue by wazerstar** [mudachyo/Blum#13]
I think that if there's any possible claims to do before playing the game, it should prioritize clicking claim before starting play, in order to maximize the the cooldown.

Next, when clicking the green emblems, I think they should be given a lease time before being clicking, because right now they are clicked before they are even shown on the screen, maybe there should be a lease of 300-1000ms to at least let them show on screen, would be more natural?

**Comment by mudachyo** [comment]
It doesn't matter, they don't track when you collect them
