### ISSUE TITLE
Dont work with updated Blum game

### ISSUE THREAD

**Issue by IlyasAtabaev731** [mudachyo/Blum#15]
Auto clicker dont collect any game elements (flowers, ice, bombs) with any browsers and other conditions

**Comment by Smyliu** [comment]
Same script not working

**Comment by joanhar1423** [comment]
ну ждем обнову скрипта)

**Comment by Mr-Mk7** [comment]
its not working

**Comment by Hinstein** [comment]
its not working

**Comment by koll13** [comment]
suka

**Comment by koll13** [comment]
gavno

**Comment by Huzaifa00011** [comment]
Yes not working please someone give me new file

**Comment by asdxzcvbf13** [comment]
> Да, не работает, пожалуйста, кто-нибудь, дайте мне новый файл.

No one will give you anything, you don't need to count on it.

**Comment by TT1410** [comment]
Hi, I managed to update this script
