### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by Parsam1989** [mudachyo/Blum#23]
Hello, don't be tired.  Apparently it doesn't work in the new version of BlumScript, thank you for supporting this script so far, will you continue to work and we will wait for the update? If yes, can you give an approximate date? thank you

**Comment by JohnChou01** [comment]
Hello，Blum has made a repair for the script and the script is no longer valid. Will new scripts be updated in the future?

**Comment by asdxzcvbf13** [comment]
не будет

> Hello，Blum has made a repair for the script and the script is no longer valid. Will new scripts be updated in the future?

not

**Comment by TT1410** [comment]
Hi, I managed to update this script
